---
dist: xenial
language: python
python: "3.8"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - DATABASE_MOLECULE_DISTRO=debian:buster-slim
    - NEXTCLOUD_MOLECULE_DISTRO=php:7.3-fpm-buster
script:
  - pipenv run molecule test --all
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
