---
- name: NextCloud | Check downloaded
  stat:
    path: "{{ nextcloud_download_path }}/{{ nextcloud_package }}"
  register: nextcloud_check

- name: NEXTCLOUD | Ensure deploy paths
  file:
    dest: "{{ item }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    state: directory
  with_items:
    - "{{ nextcloud_deploy_path }}"
  tags:
    - nextcloud_install

- name: NEXTCLOUD | Download package
  get_url:
    url: "{{ nextcloud_url }}"
    dest: "{{ nextcloud_package_path }}"
  when: not nextcloud_check.stat.exists
  tags:
    - nextcloud_install

- name: NEXTCLOUD | Extract downloaded package
  unarchive:
    src: "{{ nextcloud_package_path }}"
    dest: "{{ nextcloud_deploy_path }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    remote_src: True
  when: not nextcloud_check.stat.exists
  tags:
    - nextcloud_install

