---
# PHP
php_max_execution_time: 30
php_max_input_time: 60
php_max_input_nesting_level: 64
php_max_input_vars: 1000
php_memory_limit: 512M
php_upload_max_filesize: 2M
php_max_file_uploads: 20
php_post_max_size: 8M
php_fpm_user: "{{ nginx_user }}"
php_fpm_group: "{{ nginx_group }}"
php_fpm_socket: /run/php-fpm.sock
php_pid_file: /run/php-fpm.pid
php_fpm_service_enabled: true
php_fpm_pool_definitions:
  www:
    user: "{{ php_fpm_user }}"
    group: "{{ php_fpm_group }}"
    listen: "{{ php_fpm_socket }}"
    listen_owner: "{{ nginx_user }}"
    listen_group: "{{ nginx_group }}"
    listen_mode: "0660"
    clear_env: "no"
    pm:
      type: dynamic
      max_children: 10
      start_servers: 2
      min_spare_servers: 2
      max_spare_servers: 4

php_ini_configuration_template:
  src: "{{ playbook_dir }}/templates/php/php.ini.j2"
  dest: "/usr/local/etc/php/php.ini"

php_fpm_configuration_template:
  src: "{{ playbook_dir }}/templates/php/php-fpm.conf.j2"
  dest: "/usr/local/etc/php-fpm.conf"

php_fpm_service_configuration_template:
  src: "{{ playbook_dir }}/templates/php/php-fpm.service.j2"
  dest: "/lib/systemd/system/php-fpm.service"

php_fpm_configuration:
  log_level: notice
  process_max: 0
  daemonize: "yes"

## NGINX
nginx_version: 1.18.0
nginx_log_path: /var/log/nginx
nginx_logrotate_enabled: false
nginx_user: nginx
nginx_group: nginx
nextcloud_application_name: nextcloud

## MYSQL
mysql_user: mysql
mysql_group: mysql

# Database connections
mysql_root_user: root
nextcloud_database_user: "{{ mysql_user }}"
nextcloud_database_password: mysql

mysql_bind_addres: "0.0.0.0"
mysql_allowed_hosts: "%"
mysql_databases:
  - name: "{{ nextcloud_database_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ nextcloud_database_user }}"
    host: "{{ mysql_allowed_hosts }}"
    password: "{{ nextcloud_database_password }}"
    priv:
      - 'nextcloud.*:ALL'

# MariaDB tunning
mysql_flavour: mariadb

## Next Cloud
nextcloud_user: "{{ php_fpm_user }}"
nextcloud_group: "{{ php_fpm_group }}"
nextcloud_deploy_path: /var/www
nextcloud_root_path: "{{ nextcloud_deploy_path }}/nextcloud"
nextcloud_database_type: "mysql"
nextcloud_database_name: "nextcloud"
nextcloud_database_host: "nextclouddatabase"

## nextcloud config
nextcloud_http_overwrite: http
nextcloud_trusted_domains:
  - localhost
  - trusted.domain
  - also.trusted.domain
